[package]
name = "bradipous-curves"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
heapless = { version = "0.8.0", features = ["serde"] }
kurbo = { version = "0.10.4", default-features = false, features = ["libm"] }
libm = "0.2.8"
