[package]
name = "bradipograph"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { version = "=0.3.2", features = ["nightly", "executor-thread", "arch-riscv32"] }
embassy-time = { version = "0.1.5", features = ["generic-queue-8"] }
embedded-hal = "0.2.7"
embedded-hal-async = "1.0.0-rc.1"
esp-backtrace = { version = "0.9.0", features = ["esp32c3", "esp-println", "print-uart", "panic-handler"] }
esp-println = { version = "0.7.1", default-features = false, features = ["esp32c3"] }
esp32c3-hal = { version = "0.13.0", features = ["embassy", "embassy-time-timg0", "async"] }
