[package]
name = "bradipous-geom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []
default = ["std"]

[dependencies]
libm = "0.2.8"

[dev-dependencies]
proptest = "1.4.0"
